name: CLI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Build Docker image
        run: docker build -t mycli .

      - name: Run CLI command
        run: |
          docker run \
            -e client_id=${{ secrets.CLIENT_ID }} \
            -e client_secret=${{ secrets.CLIENT_SECRET }} \
            -e authorization_url=${{ secrets.AUTHORIZATION_URL }} \
            -e token_url=${{ secrets.TOKEN_URL }} \
            mycli "DWC spaces read -S SAP_DATASPHERE_DWC -H "https://invenics.eu10.hcs.cloud.sap/dwaas-ui/index.html#/databuilder&/db/SAP_DATASPHERE_DWC/Ravi_Employee_Details1" -m"

